--
-- PostgreSQL database dump
--

-- Dumped from database version 17.0
-- Dumped by pg_dump version 17.0

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: quiz; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.quiz (
    id integer NOT NULL,
    title character varying(255)
);


ALTER TABLE public.quiz OWNER TO postgres;

--
-- Name: quiz_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.quiz ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.quiz_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: quiz_question_ids; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.quiz_question_ids (
    quiz_id integer NOT NULL,
    question_ids integer
);


ALTER TABLE public.quiz_question_ids OWNER TO postgres;

--
-- Data for Name: quiz; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.quiz (id, title) FROM stdin;
1	JavaQuizz
2	Python Quiz
3	PHP Quiz
4	JavaScript Quiz
5	JavaScript Quiz 2
6	Python Quiz 2
\.


--
-- Data for Name: quiz_question_ids; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.quiz_question_ids (quiz_id, question_ids) FROM stdin;
1	49
1	57
1	48
1	31
1	18
2	40
2	74
2	67
2	68
2	34
2	35
2	76
2	69
2	42
2	38
3	91
3	84
3	86
3	80
3	85
3	89
3	79
3	87
3	81
3	77
4	92
4	94
4	101
4	103
4	104
4	102
4	105
4	95
4	96
4	93
5	95
6	41
6	70
6	69
6	46
6	42
6	34
6	43
6	38
6	39
6	68
6	37
6	75
6	44
6	71
6	74
6	62
6	33
6	35
6	63
6	66
\.


--
-- Name: quiz_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.quiz_id_seq', 6, true);


--
-- Name: quiz quiz_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.quiz
    ADD CONSTRAINT quiz_pkey PRIMARY KEY (id);


--
-- Name: quiz_question_ids fks0d7k0yq779g15wmctr0tlnbi; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.quiz_question_ids
    ADD CONSTRAINT fks0d7k0yq779g15wmctr0tlnbi FOREIGN KEY (quiz_id) REFERENCES public.quiz(id);


--
-- PostgreSQL database dump complete
--

